__author__ = 'barnett.io'
'''Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the
 first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the
even-valued terms.'''

def sumOfEvenFibN(fib):
    a = 1
    b = 0
    even_fib = 0
    while fib < 4000000:
        print 'Currently on Fibonacci #'+ str(fib)
        fib = a+b
        b = a
        a = fib
        if fib % 2 == 0:
            even_fib += fib
    return "The sum of all even Fibonacci numbers with values less than 4 million: " + str(even_fib)

print sumOfEvenFibN(1)